[2025-02-06T20:34:58.426+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-06T20:34:58.439+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_hooks.plot_github scheduled__2025-02-05T13:30:00+00:00 [queued]>
[2025-02-06T20:34:58.445+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_hooks.plot_github scheduled__2025-02-05T13:30:00+00:00 [queued]>
[2025-02-06T20:34:58.446+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-06T20:34:58.454+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): plot_github> on 2025-02-05 13:30:00+00:00
[2025-02-06T20:34:58.464+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=471) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-06T20:34:58.465+0000] {standard_task_runner.py:64} INFO - Started process 496 to run task
[2025-02-06T20:34:58.469+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks', 'plot_github', 'scheduled__2025-02-05T13:30:00+00:00', '--job-id', '1553', '--raw', '--subdir', 'DAGS_FOLDER/Stock_pred.py', '--cfg-path', '/tmp/tmpqjhalnl5']
[2025-02-06T20:34:58.472+0000] {standard_task_runner.py:91} INFO - Job 1553: Subtask plot_github
[2025-02-06T20:34:58.519+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgres_hooks.plot_github scheduled__2025-02-05T13:30:00+00:00 [running]> on host b7aba691e1ff
[2025-02-06T20:34:58.619+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_postgres_hooks' AIRFLOW_CTX_TASK_ID='plot_github' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T13:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-05T13:30:00+00:00'
[2025-02-06T20:34:58.620+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-06T20:35:06.861+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-06T20:35:06.862+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Stock_pred.py", line 394, in plot_github
    repo.update_file(contents.path, "committing files", content, contents.sha, branch="main")
  File "/home/airflow/.local/lib/python3.12/site-packages/github/Repository.py", line 2508, in update_file
    headers, data = self._requester.requestJsonAndCheck(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/github/Requester.py", line 548, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/github/Requester.py", line 609, in __check
    raise self.createException(status, responseHeaders, data)
github.GithubException.GithubException: 409 {"message": "is at 8145202a785c1b5c921d3c364f2c037022a0d55b but expected 7f9cc1a9419014a6ef4dedb2f582c0e7d725dbc4", "documentation_url": "https://docs.github.com/rest/repos/contents#create-or-update-file-contents", "status": "409"}
[2025-02-06T20:35:06.873+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_with_postgres_hooks, task_id=plot_github, run_id=scheduled__2025-02-05T13:30:00+00:00, execution_date=20250205T133000, start_date=20250206T203458, end_date=20250206T203506
[2025-02-06T20:35:06.881+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1553 for task plot_github (409 {"message": "is at 8145202a785c1b5c921d3c364f2c037022a0d55b but expected 7f9cc1a9419014a6ef4dedb2f582c0e7d725dbc4", "documentation_url": "https://docs.github.com/rest/repos/contents#create-or-update-file-contents", "status": "409"}; 496)
[2025-02-06T20:35:06.913+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-02-06T20:35:06.925+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-06T20:35:06.927+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
