[2024-07-21T09:35:24.021+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-21T09:35:24.033+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_hooks.get_src_tables manual__2024-07-21T09:35:20.921311+00:00 [queued]>
[2024-07-21T09:35:24.036+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_hooks.get_src_tables manual__2024-07-21T09:35:20.921311+00:00 [queued]>
[2024-07-21T09:35:24.037+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-21T09:35:24.042+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_src_tables> on 2024-07-21 09:35:20.921311+00:00
[2024-07-21T09:35:24.048+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=2731) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-21T09:35:24.049+0000] {standard_task_runner.py:64} INFO - Started process 2742 to run task
[2024-07-21T09:35:24.049+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks', 'get_src_tables', 'manual__2024-07-21T09:35:20.921311+00:00', '--job-id', '373', '--raw', '--subdir', 'DAGS_FOLDER/Stock_pred.py', '--cfg-path', '/tmp/tmpcxha5qav']
[2024-07-21T09:35:24.050+0000] {standard_task_runner.py:91} INFO - Job 373: Subtask get_src_tables
[2024-07-21T09:35:24.067+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgres_hooks.get_src_tables manual__2024-07-21T09:35:20.921311+00:00 [running]> on host d89911194c67
[2024-07-21T09:35:24.101+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_postgres_hooks' AIRFLOW_CTX_TASK_ID='get_src_tables' AIRFLOW_CTX_EXECUTION_DATE='2024-07-21T09:35:20.921311+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-21T09:35:20.921311+00:00'
[2024-07-21T09:35:24.101+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-21T09:35:24.104+0000] {base.py:84} INFO - Using connection ID 'postgres_server_2' for task execution.
[2024-07-21T09:35:24.109+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/common/sql/hooks/sql.py:269: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return psql.read_sql(sql, con=conn, params=parameters, **kwargs)

[2024-07-21T09:35:24.109+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-21T09:35:24.110+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 2262, in execute
    cur.execute(sql, *args)
psycopg2.errors.UndefinedColumn: column "date" does not exist
LINE 1:  SELECT "date", "CLOSE" FROM public."stock_time_series" 
                ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Stock_pred.py", line 51, in get_src_tables
    df_ts = hook.get_pandas_df(sql_ts)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 269, in get_pandas_df
    return psql.read_sql(sql, con=conn, params=parameters, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 654, in read_sql
    return pandas_sql.read_query(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 2326, in read_query
    cursor = self.execute(sql, params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 2274, in execute
    raise ex from exc
pandas.errors.DatabaseError: Execution failed on sql ' SELECT "date", "CLOSE" FROM public."stock_time_series" ': column "date" does not exist
LINE 1:  SELECT "date", "CLOSE" FROM public."stock_time_series" 
                ^

[2024-07-21T09:35:24.114+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_with_postgres_hooks, task_id=get_src_tables, run_id=manual__2024-07-21T09:35:20.921311+00:00, execution_date=20240721T093520, start_date=20240721T093524, end_date=20240721T093524
[2024-07-21T09:35:24.118+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 373 for task get_src_tables (Execution failed on sql ' SELECT "date", "CLOSE" FROM public."stock_time_series" ': column "date" does not exist
LINE 1:  SELECT "date", "CLOSE" FROM public."stock_time_series" 
                ^
; 2742)
[2024-07-21T09:35:24.148+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-21T09:35:24.158+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-21T09:35:24.160+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
