[2024-07-22T08:59:02.181+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T08:59:02.189+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_hooks.featur_engineer manual__2024-07-22T08:58:51.094531+00:00 [queued]>
[2024-07-22T08:59:02.192+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_hooks.featur_engineer manual__2024-07-22T08:58:51.094531+00:00 [queued]>
[2024-07-22T08:59:02.192+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T08:59:02.197+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): featur_engineer> on 2024-07-22 08:58:51.094531+00:00
[2024-07-22T08:59:02.201+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=4734) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T08:59:02.202+0000] {standard_task_runner.py:64} INFO - Started process 4745 to run task
[2024-07-22T08:59:02.202+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks', 'featur_engineer', 'manual__2024-07-22T08:58:51.094531+00:00', '--job-id', '515', '--raw', '--subdir', 'DAGS_FOLDER/Stock_pred.py', '--cfg-path', '/tmp/tmpm75am9ze']
[2024-07-22T08:59:02.203+0000] {standard_task_runner.py:91} INFO - Job 515: Subtask featur_engineer
[2024-07-22T08:59:02.219+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgres_hooks.featur_engineer manual__2024-07-22T08:58:51.094531+00:00 [running]> on host d89911194c67
[2024-07-22T08:59:02.247+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_postgres_hooks' AIRFLOW_CTX_TASK_ID='featur_engineer' AIRFLOW_CTX_EXECUTION_DATE='2024-07-22T08:58:51.094531+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-22T08:58:51.094531+00:00'
[2024-07-22T08:59:02.248+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T08:59:02.906+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T08:59:02.907+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Stock_pred.py", line 213, in transform_data
    on_balance_volume(df)
  File "/opt/airflow/dags/Stock_pred.py", line 198, in on_balance_volume
    if index > 0:
       ^^^^^^^^^
TypeError: '>' not supported between instances of 'str' and 'int'
[2024-07-22T08:59:02.911+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_with_postgres_hooks, task_id=featur_engineer, run_id=manual__2024-07-22T08:58:51.094531+00:00, execution_date=20240722T085851, start_date=20240722T085902, end_date=20240722T085902
[2024-07-22T08:59:02.917+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 515 for task featur_engineer ('>' not supported between instances of 'str' and 'int'; 4745)
[2024-07-22T08:59:02.959+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-22T08:59:02.969+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-22T08:59:02.971+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
